---
# tasks file for firewall_configuration
- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes

- name: Create iptables backup
  community.general.iptables_state:
    state: saved
    path: "{{ iptables_backup_path }}"

- name: Allow established sessions
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow loopback traffic
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  become: true

- name: Allow HTTP
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  become: true

- name: Allow HTTPS
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
  become: true

- name: Deny all other traffic
  iptables:
    chain: INPUT
    policy: DROP
  become: true

- name: Save iptables rules
  community.general.iptables_state:
    state: saved
    path: "{{ iptables_path }}"
